/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paintbasico;

import java.awt.Color;
import javax.swing.JFileChooser;

/**
 *
 * @author Jota
 */
public class mainVentana extends javax.swing.JFrame {

    /**
     * Creates new form mainVentana
     */
    public mainVentana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toolsButtonsGroup = new javax.swing.ButtonGroup();
        colorsButtonsGroup = new javax.swing.ButtonGroup();
        panel_toolBar = new javax.swing.JPanel();
        toolBar = new javax.swing.JToolBar();
        pencilButton = new javax.swing.JToggleButton();
        lineButton = new javax.swing.JToggleButton();
        rectangleButton = new javax.swing.JToggleButton();
        ovalButton = new javax.swing.JToggleButton();
        panel_toolBar2 = new javax.swing.JPanel();
        statusLabel = new javax.swing.JLabel();
        fillButton = new javax.swing.JCheckBox();
        panel_color = new javax.swing.JPanel();
        blackColor = new javax.swing.JToggleButton();
        redColor = new javax.swing.JToggleButton();
        blueColor = new javax.swing.JToggleButton();
        whiteColor = new javax.swing.JToggleButton();
        yellowColor = new javax.swing.JToggleButton();
        greenColor = new javax.swing.JToggleButton();
        lienzo = new paintbasico.Lienzo();
        menuBar = new javax.swing.JMenuBar();
        menuButton = new javax.swing.JMenu();
        newButton = new javax.swing.JMenuItem();
        openButton = new javax.swing.JMenuItem();
        saveButton = new javax.swing.JMenuItem();
        editButton = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        FormListener formListener = new FormListener();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1300, 1300));
        setSize(new java.awt.Dimension(250, 250));

        panel_toolBar.setLayout(new java.awt.BorderLayout());

        toolBar.setRollover(true);

        toolsButtonsGroup.add(pencilButton);
        pencilButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Jota\\Desktop\\SMM\\Practica4\\iconos\\Lapiz.gif")); // NOI18N
        pencilButton.setFocusable(false);
        pencilButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pencilButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pencilButton.addActionListener(formListener);
        toolBar.add(pencilButton);

        toolsButtonsGroup.add(lineButton);
        lineButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Jota\\Desktop\\SMM\\Practica4\\iconos\\Linea.gif")); // NOI18N
        lineButton.setFocusable(false);
        lineButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lineButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lineButton.addActionListener(formListener);
        toolBar.add(lineButton);

        toolsButtonsGroup.add(rectangleButton);
        rectangleButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Jota\\Desktop\\SMM\\Practica4\\iconos\\Rectangulo.gif")); // NOI18N
        rectangleButton.setFocusable(false);
        rectangleButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rectangleButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        rectangleButton.addActionListener(formListener);
        toolBar.add(rectangleButton);

        toolsButtonsGroup.add(ovalButton);
        ovalButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Jota\\Desktop\\SMM\\Practica4\\iconos\\Ovalo.gif")); // NOI18N
        ovalButton.setFocusable(false);
        ovalButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ovalButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ovalButton.addActionListener(formListener);
        toolBar.add(ovalButton);

        panel_toolBar.add(toolBar, java.awt.BorderLayout.CENTER);

        getContentPane().add(panel_toolBar, java.awt.BorderLayout.PAGE_START);

        panel_toolBar2.setLayout(new java.awt.BorderLayout());

        statusLabel.setText("none");
        statusLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        panel_toolBar2.add(statusLabel, java.awt.BorderLayout.SOUTH);

        fillButton.setText("Relleno");
        fillButton.addActionListener(formListener);
        panel_toolBar2.add(fillButton, java.awt.BorderLayout.LINE_END);

        panel_color.setLayout(new java.awt.GridLayout(2, 3));

        blackColor.setBackground(new java.awt.Color(0, 0, 0));
        colorsButtonsGroup.add(blackColor);
        blackColor.setMargin(new java.awt.Insets(2, 2, 2, 2));
        blackColor.addActionListener(formListener);
        panel_color.add(blackColor);

        redColor.setBackground(new java.awt.Color(255, 0, 0));
        colorsButtonsGroup.add(redColor);
        redColor.addActionListener(formListener);
        panel_color.add(redColor);

        blueColor.setBackground(java.awt.Color.blue);
        colorsButtonsGroup.add(blueColor);
        blueColor.addActionListener(formListener);
        panel_color.add(blueColor);

        whiteColor.setBackground(new java.awt.Color(255, 255, 255));
        colorsButtonsGroup.add(whiteColor);
        whiteColor.addActionListener(formListener);
        panel_color.add(whiteColor);

        yellowColor.setBackground(java.awt.Color.yellow);
        colorsButtonsGroup.add(yellowColor);
        yellowColor.addActionListener(formListener);
        panel_color.add(yellowColor);

        greenColor.setBackground(java.awt.Color.green);
        colorsButtonsGroup.add(greenColor);
        greenColor.addActionListener(formListener);
        panel_color.add(greenColor);

        panel_toolBar2.add(panel_color, java.awt.BorderLayout.LINE_START);

        getContentPane().add(panel_toolBar2, java.awt.BorderLayout.SOUTH);

        javax.swing.GroupLayout lienzoLayout = new javax.swing.GroupLayout(lienzo);
        lienzo.setLayout(lienzoLayout);
        lienzoLayout.setHorizontalGroup(
            lienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        lienzoLayout.setVerticalGroup(
            lienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 299, Short.MAX_VALUE)
        );

        getContentPane().add(lienzo, java.awt.BorderLayout.CENTER);

        menuButton.setText("File");

        newButton.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        newButton.setText("New");
        newButton.addActionListener(formListener);
        menuButton.add(newButton);

        openButton.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        openButton.setText("Open");
        openButton.addActionListener(formListener);
        menuButton.add(openButton);

        saveButton.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        saveButton.setText("Save");
        saveButton.addActionListener(formListener);
        menuButton.add(saveButton);

        menuBar.add(menuButton);

        editButton.setText("Edit");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("View toolbar");
        jMenuItem1.addActionListener(formListener);
        editButton.add(jMenuItem1);

        menuBar.add(editButton);

        setJMenuBar(menuBar);

        pack();
    }

    // Code for dispatching events from components to event handlers.

    private class FormListener implements java.awt.event.ActionListener {
        FormListener() {}
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            if (evt.getSource() == pencilButton) {
                mainVentana.this.pencilButtonActionPerformed(evt);
            }
            else if (evt.getSource() == lineButton) {
                mainVentana.this.lineButtonActionPerformed(evt);
            }
            else if (evt.getSource() == rectangleButton) {
                mainVentana.this.rectangleButtonActionPerformed(evt);
            }
            else if (evt.getSource() == ovalButton) {
                mainVentana.this.ovalButtonActionPerformed(evt);
            }
            else if (evt.getSource() == blackColor) {
                mainVentana.this.blackColorActionPerformed(evt);
            }
            else if (evt.getSource() == redColor) {
                mainVentana.this.redColorActionPerformed(evt);
            }
            else if (evt.getSource() == blueColor) {
                mainVentana.this.blueColorActionPerformed(evt);
            }
            else if (evt.getSource() == whiteColor) {
                mainVentana.this.whiteColorActionPerformed(evt);
            }
            else if (evt.getSource() == yellowColor) {
                mainVentana.this.yellowColorActionPerformed(evt);
            }
            else if (evt.getSource() == greenColor) {
                mainVentana.this.greenColorActionPerformed(evt);
            }
            else if (evt.getSource() == fillButton) {
                mainVentana.this.fillButtonActionPerformed(evt);
            }
            else if (evt.getSource() == newButton) {
                mainVentana.this.newButtonActionPerformed(evt);
            }
            else if (evt.getSource() == openButton) {
                mainVentana.this.openButtonActionPerformed(evt);
            }
            else if (evt.getSource() == saveButton) {
                mainVentana.this.saveButtonActionPerformed(evt);
            }
            else if (evt.getSource() == jMenuItem1) {
                mainVentana.this.jMenuItem1ActionPerformed(evt);
            }
        }
    }// </editor-fold>//GEN-END:initComponents

    private void pencilButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pencilButtonActionPerformed
        this.lienzo.setShape(1);
        this.statusLabel.setText("Pencil");
    }//GEN-LAST:event_pencilButtonActionPerformed

    private void lineButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lineButtonActionPerformed
        this.lienzo.setShape(2);
        this.statusLabel.setText("Line");
    }//GEN-LAST:event_lineButtonActionPerformed

    private void rectangleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rectangleButtonActionPerformed
        this.lienzo.setShape(3);
        this.statusLabel.setText("Rectangle");
    }//GEN-LAST:event_rectangleButtonActionPerformed

    private void ovalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ovalButtonActionPerformed
        this.lienzo.setShape(4);
        this.statusLabel.setText("Oval");
    }//GEN-LAST:event_ovalButtonActionPerformed

    private void blackColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blackColorActionPerformed
        color = Color.black;
        this.lienzo.setColor(color);
    }//GEN-LAST:event_blackColorActionPerformed

    private void redColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redColorActionPerformed
        color = Color.red;
        this.lienzo.setColor(color);
    }//GEN-LAST:event_redColorActionPerformed

    private void blueColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blueColorActionPerformed
        color = Color.blue;
        this.lienzo.setColor(color);
    }//GEN-LAST:event_blueColorActionPerformed

    private void whiteColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_whiteColorActionPerformed
        color = Color.white;
        this.lienzo.setColor(color);
    }//GEN-LAST:event_whiteColorActionPerformed

    private void yellowColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yellowColorActionPerformed
        color = Color.yellow;
        this.lienzo.setColor(color);
    }//GEN-LAST:event_yellowColorActionPerformed

    private void greenColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_greenColorActionPerformed
        color = Color.green;
        this.lienzo.setColor(color);
    }//GEN-LAST:event_greenColorActionPerformed

    private void fillButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fillButtonActionPerformed
        this.lienzo.setFilled();
    }//GEN-LAST:event_fillButtonActionPerformed

    private void newButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newButtonActionPerformed
        this.lienzo.reset();
        
    }//GEN-LAST:event_newButtonActionPerformed

    private void openButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openButtonActionPerformed
        JFileChooser dlg = new JFileChooser();
        int resp = dlg.showOpenDialog(this);
        
    }//GEN-LAST:event_openButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        JFileChooser dlg = new JFileChooser();
        int resp = dlg.showSaveDialog(this);
        
    }//GEN-LAST:event_saveButtonActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        if(showToolBar){
            this.statusLabel.setVisible(!showToolBar);
            showToolBar = false;
        }else{
            this.statusLabel.setVisible(!showToolBar);
            showToolBar = true;
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainVentana().setVisible(true);
            }
        });
    }

    //Variables propias
    private Color color = Color.black;
    private boolean showToolBar = true;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton blackColor;
    private javax.swing.JToggleButton blueColor;
    private javax.swing.ButtonGroup colorsButtonsGroup;
    private javax.swing.JMenu editButton;
    private javax.swing.JCheckBox fillButton;
    private javax.swing.JToggleButton greenColor;
    private javax.swing.JMenuItem jMenuItem1;
    private paintbasico.Lienzo lienzo;
    private javax.swing.JToggleButton lineButton;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuButton;
    private javax.swing.JMenuItem newButton;
    private javax.swing.JMenuItem openButton;
    private javax.swing.JToggleButton ovalButton;
    private javax.swing.JPanel panel_color;
    private javax.swing.JPanel panel_toolBar;
    private javax.swing.JPanel panel_toolBar2;
    private javax.swing.JToggleButton pencilButton;
    private javax.swing.JToggleButton rectangleButton;
    private javax.swing.JToggleButton redColor;
    private javax.swing.JMenuItem saveButton;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JToolBar toolBar;
    private javax.swing.ButtonGroup toolsButtonsGroup;
    private javax.swing.JToggleButton whiteColor;
    private javax.swing.JToggleButton yellowColor;
    // End of variables declaration//GEN-END:variables
}
