/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practicafinal;

import com.github.sarxos.webcam.Webcam;
import java.awt.image.BufferedImage;
import java.io.File;
import javafx.scene.Camera;
import javax.swing.JInternalFrame;
import sm.jj.iu.Lienzo2DImagen;
import uk.co.caprica.vlcj.player.embedded.EmbeddedMediaPlayer;

/**
 * Clase padre de todos los tipos de ventanas.
 * 
 * Hereda de javax.swing.JInternalFrame
 * 
 * @author Jota
 */
public abstract class InternalWindowSM extends javax.swing.JInternalFrame {

    /**
     * Creates new form internalWindowSM
     */
    public InternalWindowSM() {
        initComponents();
    }
    
    /**
     * Abstract : debe devolver un objeto Webcam
     * 
     * @return objeto WebCam
     */
    public abstract Webcam getCam();
    
    /**
     * Abstract : debe devolver la captura de la imagen
     * 
     * @param f objeto tipo File
     * @return  captura
     */
    public abstract EmbeddedMediaPlayer getShot(File f);
    
    /**
     * Abstract : devuelve una imagen
     * 
     * @return objeto BufferedImage
     */
    public abstract BufferedImage getImage();
    
    /**
     * Abstract : devuelve el lienzo imagen
     * 
     * @return objeto Lienzo2DImagen
     */
    public abstract Lienzo2DImagen getLienzo();
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(300, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
