/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practicafinal;

import com.github.sarxos.webcam.Webcam;
import com.github.sarxos.webcam.WebcamPanel;
import java.awt.BorderLayout;
import java.awt.image.BufferedImage;
import java.io.File;
import javafx.scene.Camera;
import sm.jj.iu.Lienzo2DImagen;
import uk.co.caprica.vlcj.player.embedded.EmbeddedMediaPlayer;

/**
 * Ventana Interna tipo Camara
 * 
 * Hereda de InternalWindowSM
 * 
 * @author Jota
 */
public class InternalCameraWindow extends InternalWindowSM {
    /**
     * Camara : objeto tipo Webcam
     */
    private Webcam camara = null;
    
    /**
     * Constructor de la clase
     */
    private InternalCameraWindow() {
        initComponents();
        camara = Webcam.getDefault();
        if ( camara != null ){
            WebcamPanel areaVisual = new WebcamPanel(camara);
            if(areaVisual != null){
                getContentPane().add(areaVisual,BorderLayout.CENTER);
                pack();
            }
            
        }
    }
    
    /**
     * Devuelve la camara del objeto ventana
     * 
     * @return camara tipo WebCam
     */
    public static InternalCameraWindow getInstance(){
        InternalCameraWindow v = new InternalCameraWindow();
        return (v.camara != null?v:null);
    }
    
    /**
     * Apaga la camara 
     * 
     */
    public void close(){
        if (camara != null){
            try{
                camara.close();
            }catch(Exception e){
                System.err.println("InternalCameraWindow0"+e);
            }
        }
    }
       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new java.awt.BorderLayout());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Devuelve la camara
     * 
     * @return camara objeto WebCam
     */
    @Override
    public Webcam getCam() {
        return camara;
    }

    /**
     * No devuelve nada , para control de ventanas
     * 
     * @param f
     * @return null
     */
    @Override
    public EmbeddedMediaPlayer getShot(File f) {
        return null;
    }
    
    /**
     * Devuelve la imagen de la camara
     * 
     * @return camara.getImage() retorna un objeto bufferedImage
     */
    @Override
    public BufferedImage getImage() {
        return camara.getImage();
    }

    /**
     * No devuelve nada , para control de ventanas
     * 
     * @return null
     */  
    @Override
    public Lienzo2DImagen getLienzo() {
        return null;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
