/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practicafinal;

import com.github.sarxos.webcam.Webcam;
import java.awt.image.BufferedImage;
import java.io.File;
import javafx.scene.Camera;
import sm.jj.iu.Lienzo2DImagen;
import uk.co.caprica.vlcj.component.EmbeddedMediaPlayerComponent;
import uk.co.caprica.vlcj.player.embedded.EmbeddedMediaPlayer;

/**
 * Ventana de tipo video
 * 
 * Hereda de InternalWindowSM
 * 
 * @author Jota
 */
public class InternalVideoWindow extends InternalWindowSM {
    
    /**
     * vlcplayer : objeto de tipo EmbeddedMediaPlayer
     * fMedia : objeto de tipo File 
     */
    private EmbeddedMediaPlayer vlcplayer = null;
    private File fMedia;
    
    
    /**
     * Constructor de la clase
     */
    private InternalVideoWindow(File f) {
        initComponents();
        fMedia = f;
        EmbeddedMediaPlayerComponent aVisual = new EmbeddedMediaPlayerComponent();
        getContentPane().add(aVisual,java.awt.BorderLayout.CENTER);
        vlcplayer = aVisual.getMediaPlayer();
    }
    
    /**
     * Devuelve el objeto vlcplayer de la venta de tipo InternalVideoWindow
     * 
     * @param f tipo de archivo
     * @return v ventana interna de tipo video
     */
    public static InternalVideoWindow getInstance(File f){
       InternalVideoWindow v = new InternalVideoWindow(f);
       return (v.vlcplayer!=null?v:null);
    }
    
    /**
     * Reproduce un video
     * 
     */
    public void play(){
        if(vlcplayer != null){
            if(vlcplayer.isPlayable()){
                vlcplayer.play();
            }
            else{
                vlcplayer.playMedia(fMedia.getAbsolutePath());
            }
        }
    }
    
    /**
     * Pausa o revovina el video
     * 
     */
    public void stop(){
        if(vlcplayer != null){
            if(vlcplayer.isPlaying()){
                vlcplayer.pause();
            }else{
                vlcplayer.stop();
            }
               
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        playButton = new javax.swing.JButton();
        stopButton = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        playButton.setText("Play");
        playButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playButtonActionPerformed(evt);
            }
        });
        jPanel1.add(playButton);

        stopButton.setText("Stop");
        stopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopButtonActionPerformed(evt);
            }
        });
        jPanel1.add(stopButton);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void playButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playButtonActionPerformed
        play();
    }//GEN-LAST:event_playButtonActionPerformed

    private void stopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopButtonActionPerformed
        stop();
    }//GEN-LAST:event_stopButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton playButton;
    private javax.swing.JButton stopButton;
    // End of variables declaration//GEN-END:variables

    /**
     * No devuelve nada , para control de ventanas
     * 
     * @return 
     */
    @Override
    public Webcam getCam() {
        return null;
    }

    /**
     * Devuelve vlcplayer del objeto de la clase InternalVideoWindow
     * 
     * @param f
     * @return 
     */
    @Override
    public EmbeddedMediaPlayer getShot(File f) {
        return vlcplayer;
    }
    
    /**
     * No devuelve nada , para control de ventanas
     * 
     * @return 
     */
    @Override
    public BufferedImage getImage() {
        return null;
    }

    /**
     * No devuelve nada , para control de ventanas
     * 
     * @return 
     */
    @Override
    public Lienzo2DImagen getLienzo() {
        return null;
    }
}
